name: url_launcher_plus
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/swarajkumarsingh/url_launcher_plus

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
